Week2
Numpy Exercises

In [ ]:
import numpy as np

In [ ]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [ ]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [ ]:
sequence_of_integers = np.arange(5, 12) #Generates array includes 5 to 12(not considered) values.
print(sequence_of_integers)             #np.zeros and np.ones fills array with one or zero depends on function name.

[ 5  6  7  8  9 10 11]


In [ ]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6)) 
# np.random.randint can fill the array random numbers within specified boundaries.                                                                                 
print(random_integers_between_50_and_100)

[57 86 89 84 63 54]


In [ ]:
random_floats_between_0_and_1 = np.random.random([6]) #random floating point values.
print(random_floats_between_0_and_1) 

[0.19462855 0.06071927 0.96233074 0.0010889  0.61382317 0.16284565]


In [ ]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0 
print(random_floats_between_2_and_3)

[2.19462855 2.06071927 2.96233074 2.0010889  2.61382317 2.16284565]


In [ ]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[252 171 270 267 273 153]


In [ ]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[252 171 270 267 273 153]


In [ ]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[-0.09251196  0.50665276  0.94669357 -1.15955696 -0.52630185 -0.55943978
 -0.00721243 -0.4944851  -1.40527083 -0.08242134  0.13705353 -1.67724641
  0.53094986 -1.28484241  0.21688197]
[21.90748804 25.50665276 28.94669357 29.84044304 33.47369815 36.44056022
 39.99278757 42.5055149  44.59472917 48.91757866 52.13705353 53.32275359
 58.53094986 59.71515759 64.21688197]


Pandas Exercises

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [ ]:
# Create a new column named adjusted.
my_dataframe["adjusted"] = my_dataframe["activity"] + 2

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [ ]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

Rows #0, #1, and #2:
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 

Row #2:
   temperature  activity  adjusted
2           20         9        11 

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int64


In [ ]:
#@title Double-click for a solution to Task 1.

# Create a Python list that holds the names of the four columns.
my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

# Create a 3x4 numpy array, each cell populated with a random integer.
my_data = np.random.randint(low=0, high=101, size=(3, 4))

# Create a DataFrame.
df = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(df)

# Print the value in row #1 of the Eleanor column.
print("\nSecond row of the Eleanor column: %d\n" % df['Eleanor'][1])

# Create a column named Janet whose contents are the sum
# of two other columns.
df['Janet'] = df['Tahani'] + df['Jason']

# Print the enhanced DataFrame
print(df)

   Eleanor  Chidi  Tahani  Jason
0       22     28     100     72
1       96     36      53     53
2        5     88      35     91

Second row of the Eleanor column: 96

   Eleanor  Chidi  Tahani  Jason  Janet
0       22     28     100     72    172
1       96     36      53     53    106
2        5     88      35     91    126


In [ ]:
# Create a reference by assigning my_dataframe to a new variable.
print("Experiment with a reference:")
reference_to_df = df

# Print the starting value of a particular cell.
print("  Starting value of df: %d" % df['Jason'][1])
print("  Starting value of reference_to_df: %d\n" % reference_to_df['Jason'][1])

# Modify a cell in df.
df.at[1, 'Jason'] = df['Jason'][1] + 5
print("  Updated df: %d" % df['Jason'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])

# Create a true copy of my_dataframe
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Print the starting value of a particular cell.
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

# Modify a cell in df.
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])

Experiment with a reference:
  Starting value of df: 53
  Starting value of reference_to_df: 53

  Updated df: 58
  Updated reference_to_df: 58


Experiment with a true copy:
  Starting value of my_dataframe: 7
  Starting value of copy_of_my_dataframe: 7

  Updated my_dataframe: 10
  copy_of_my_dataframe does not get updated: 7
